# Generated by Django 3.2.4 on 2021-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=45)),
                ('post_add', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=50)),
                ('address_detail', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('sms_reception', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('email_reception', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
