# Generated by Django 3.2.4 on 2021-06-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='order',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
