# Generated by Django 3.2.4 on 2021-06-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('orders', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='OrderItem',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
