# Generated by Django 3.2.3 on 2021-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
