# Generated by Django 3.2.4 on 2021-06-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210613_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body_img',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body_size',
        ),
    ]
